# Generated by Django 5.2.3 on 2025-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_userclient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("model", "Model"),
                    ("manager", "Manager"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=12,
            ),
        ),
    ]
