# Generated by Django 5.2.3 on 2025-11-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("tron", "Tron"),
                            ("bitcoin", "Bitcoin"),
                        ],
                        editable=False,
                        max_length=12,
                    ),
                ),
                ("xpub", models.TextField(editable=False, null=True)),
                ("mnemonic", models.TextField(editable=False, null=True)),
                ("key", models.TextField(editable=False, null=True)),
                ("address", models.TextField(editable=False, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="client.client",
                    ),
                ),
            ],
        ),
    ]
