# Generated by Django 5.2.3 on 2025-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[
                    ("ethereum", "Ethereum"),
                    ("tron", "Tron"),
                    ("bitcoin", "Bitcoin"),
                ],
                max_length=12,
            ),
        ),
    ]
