# Generated by Django 5.2.3 on 2025-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="subscription_id",
            field=models.TextField(null=True),
        ),
    ]
